apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  labels:
    deployment: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      name: producer
      labels:
        app: producer
    spec:
      containers:
        - name: producer-container
          image: pashonokk/producer-service:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always

      